// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: server/api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	config "pipegraph/config"
	graph "pipegraph/graph"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nothing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nothing) Reset() {
	*x = Nothing{}
	mi := &file_server_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nothing) ProtoMessage() {}

func (x *Nothing) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nothing.ProtoReflect.Descriptor instead.
func (*Nothing) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{0}
}

type GraphState struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	NodeStates    map[uint64]graph.NodeState `protobuf:"bytes,1,rep,name=NodeStates,proto3" json:"NodeStates,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=api.NodeState"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphState) Reset() {
	*x = GraphState{}
	mi := &file_server_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphState) ProtoMessage() {}

func (x *GraphState) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphState.ProtoReflect.Descriptor instead.
func (*GraphState) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *GraphState) GetNodeStates() map[uint64]graph.NodeState {
	if x != nil {
		return x.NodeStates
	}
	return nil
}

var File_server_api_api_proto protoreflect.FileDescriptor

const file_server_api_api_proto_rawDesc = "" +
	"\n" +
	"\x14server/api/api.proto\x12\x03api\x1a\x12config/graph.proto\x1a\x10graph/node.proto\"\t\n" +
	"\aNothing\"\x9c\x01\n" +
	"\n" +
	"GraphState\x12?\n" +
	"\n" +
	"NodeStates\x18\x01 \x03(\v2\x1f.api.GraphState.NodeStatesEntryR\n" +
	"NodeStates\x1aM\n" +
	"\x0fNodeStatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\x0e2\x0e.api.NodeStateR\x05value:\x028\x012}\n" +
	"\x05Graph\x12&\n" +
	"\aGetInfo\x12\f.api.Nothing\x1a\r.config.Graph\x12)\n" +
	"\bGetState\x12\f.api.Nothing\x1a\x0f.api.GraphState\x12!\n" +
	"\x03Run\x12\f.api.Nothing\x1a\f.api.NothingB\x16Z\x14pipegraph/server/apib\x06proto3"

var (
	file_server_api_api_proto_rawDescOnce sync.Once
	file_server_api_api_proto_rawDescData []byte
)

func file_server_api_api_proto_rawDescGZIP() []byte {
	file_server_api_api_proto_rawDescOnce.Do(func() {
		file_server_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_api_api_proto_rawDesc), len(file_server_api_api_proto_rawDesc)))
	})
	return file_server_api_api_proto_rawDescData
}

var file_server_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_server_api_api_proto_goTypes = []any{
	(*Nothing)(nil),      // 0: api.Nothing
	(*GraphState)(nil),   // 1: api.GraphState
	nil,                  // 2: api.GraphState.NodeStatesEntry
	(graph.NodeState)(0), // 3: api.NodeState
	(*config.Graph)(nil), // 4: config.Graph
}
var file_server_api_api_proto_depIdxs = []int32{
	2, // 0: api.GraphState.NodeStates:type_name -> api.GraphState.NodeStatesEntry
	3, // 1: api.GraphState.NodeStatesEntry.value:type_name -> api.NodeState
	0, // 2: api.Graph.GetInfo:input_type -> api.Nothing
	0, // 3: api.Graph.GetState:input_type -> api.Nothing
	0, // 4: api.Graph.Run:input_type -> api.Nothing
	4, // 5: api.Graph.GetInfo:output_type -> config.Graph
	1, // 6: api.Graph.GetState:output_type -> api.GraphState
	0, // 7: api.Graph.Run:output_type -> api.Nothing
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_server_api_api_proto_init() }
func file_server_api_api_proto_init() {
	if File_server_api_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_api_api_proto_rawDesc), len(file_server_api_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_api_api_proto_goTypes,
		DependencyIndexes: file_server_api_api_proto_depIdxs,
		MessageInfos:      file_server_api_api_proto_msgTypes,
	}.Build()
	File_server_api_api_proto = out.File
	file_server_api_api_proto_goTypes = nil
	file_server_api_api_proto_depIdxs = nil
}
