// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: graph/config.proto

package graph

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	job "pipegraph/job"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStatus int32

const (
	NodeStatus_Waiting  NodeStatus = 0
	NodeStatus_Running  NodeStatus = 1
	NodeStatus_Finished NodeStatus = 2
	NodeStatus_Failed   NodeStatus = 3
	NodeStatus_Stopped  NodeStatus = 4
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "Waiting",
		1: "Running",
		2: "Finished",
		3: "Failed",
		4: "Stopped",
	}
	NodeStatus_value = map[string]int32{
		"Waiting":  0,
		"Running":  1,
		"Finished": 2,
		"Failed":   3,
		"Stopped":  4,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_graph_config_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_graph_config_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_graph_config_proto_rawDescGZIP(), []int{0}
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeConfig          `protobuf:"bytes,1,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	Edges         []*EdgeConfig          `protobuf:"bytes,2,rep,name=Edges,proto3" json:"Edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_graph_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_graph_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_graph_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetNodes() []*NodeConfig {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Config) GetEdges() []*EdgeConfig {
	if x != nil {
		return x.Edges
	}
	return nil
}

type NodeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=Id,proto3,oneof" json:"Id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=Name,proto3,oneof" json:"Name,omitempty"`
	Job           *job.Config            `protobuf:"bytes,3,opt,name=Job,proto3,oneof" json:"Job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_graph_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_graph_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_graph_config_proto_rawDescGZIP(), []int{1}
}

func (x *NodeConfig) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *NodeConfig) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *NodeConfig) GetJob() *job.Config {
	if x != nil {
		return x.Job
	}
	return nil
}

type EdgeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    *uint64                `protobuf:"varint,1,opt,name=FromNodeId,proto3,oneof" json:"FromNodeId,omitempty"`
	ToNodeId      *uint64                `protobuf:"varint,2,opt,name=ToNodeId,proto3,oneof" json:"ToNodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeConfig) Reset() {
	*x = EdgeConfig{}
	mi := &file_graph_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeConfig) ProtoMessage() {}

func (x *EdgeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_graph_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeConfig.ProtoReflect.Descriptor instead.
func (*EdgeConfig) Descriptor() ([]byte, []int) {
	return file_graph_config_proto_rawDescGZIP(), []int{2}
}

func (x *EdgeConfig) GetFromNodeId() uint64 {
	if x != nil && x.FromNodeId != nil {
		return *x.FromNodeId
	}
	return 0
}

func (x *EdgeConfig) GetToNodeId() uint64 {
	if x != nil && x.ToNodeId != nil {
		return *x.ToNodeId
	}
	return 0
}

var File_graph_config_proto protoreflect.FileDescriptor

const file_graph_config_proto_rawDesc = "" +
	"\n" +
	"\x12graph/config.proto\x12\x05graph\x1a\x10job/config.proto\"Z\n" +
	"\x06Config\x12'\n" +
	"\x05Nodes\x18\x01 \x03(\v2\x11.graph.NodeConfigR\x05Nodes\x12'\n" +
	"\x05Edges\x18\x02 \x03(\v2\x11.graph.EdgeConfigR\x05Edges\"v\n" +
	"\n" +
	"NodeConfig\x12\x13\n" +
	"\x02Id\x18\x01 \x01(\x04H\x00R\x02Id\x88\x01\x01\x12\x17\n" +
	"\x04Name\x18\x02 \x01(\tH\x01R\x04Name\x88\x01\x01\x12\"\n" +
	"\x03Job\x18\x03 \x01(\v2\v.job.ConfigH\x02R\x03Job\x88\x01\x01B\x05\n" +
	"\x03_IdB\a\n" +
	"\x05_NameB\x06\n" +
	"\x04_Job\"n\n" +
	"\n" +
	"EdgeConfig\x12#\n" +
	"\n" +
	"FromNodeId\x18\x01 \x01(\x04H\x00R\n" +
	"FromNodeId\x88\x01\x01\x12\x1f\n" +
	"\bToNodeId\x18\x02 \x01(\x04H\x01R\bToNodeId\x88\x01\x01B\r\n" +
	"\v_FromNodeIdB\v\n" +
	"\t_ToNodeId*M\n" +
	"\n" +
	"NodeStatus\x12\v\n" +
	"\aWaiting\x10\x00\x12\v\n" +
	"\aRunning\x10\x01\x12\f\n" +
	"\bFinished\x10\x02\x12\n" +
	"\n" +
	"\x06Failed\x10\x03\x12\v\n" +
	"\aStopped\x10\x04B\x11Z\x0fpipegraph/graphb\x06proto3"

var (
	file_graph_config_proto_rawDescOnce sync.Once
	file_graph_config_proto_rawDescData []byte
)

func file_graph_config_proto_rawDescGZIP() []byte {
	file_graph_config_proto_rawDescOnce.Do(func() {
		file_graph_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_config_proto_rawDesc), len(file_graph_config_proto_rawDesc)))
	})
	return file_graph_config_proto_rawDescData
}

var file_graph_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_graph_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_graph_config_proto_goTypes = []any{
	(NodeStatus)(0),    // 0: graph.NodeStatus
	(*Config)(nil),     // 1: graph.Config
	(*NodeConfig)(nil), // 2: graph.NodeConfig
	(*EdgeConfig)(nil), // 3: graph.EdgeConfig
	(*job.Config)(nil), // 4: job.Config
}
var file_graph_config_proto_depIdxs = []int32{
	2, // 0: graph.Config.Nodes:type_name -> graph.NodeConfig
	3, // 1: graph.Config.Edges:type_name -> graph.EdgeConfig
	4, // 2: graph.NodeConfig.Job:type_name -> job.Config
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_graph_config_proto_init() }
func file_graph_config_proto_init() {
	if File_graph_config_proto != nil {
		return
	}
	file_graph_config_proto_msgTypes[1].OneofWrappers = []any{}
	file_graph_config_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_config_proto_rawDesc), len(file_graph_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_graph_config_proto_goTypes,
		DependencyIndexes: file_graph_config_proto_depIdxs,
		EnumInfos:         file_graph_config_proto_enumTypes,
		MessageInfos:      file_graph_config_proto_msgTypes,
	}.Build()
	File_graph_config_proto = out.File
	file_graph_config_proto_goTypes = nil
	file_graph_config_proto_depIdxs = nil
}
