// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: graph/node.proto

package graph

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeState int32

const (
	NodeState_Waiting  NodeState = 0
	NodeState_Running  NodeState = 1
	NodeState_Finished NodeState = 2
	NodeState_Failed   NodeState = 3
	NodeState_Stopped  NodeState = 4
)

// Enum value maps for NodeState.
var (
	NodeState_name = map[int32]string{
		0: "Waiting",
		1: "Running",
		2: "Finished",
		3: "Failed",
		4: "Stopped",
	}
	NodeState_value = map[string]int32{
		"Waiting":  0,
		"Running":  1,
		"Finished": 2,
		"Failed":   3,
		"Stopped":  4,
	}
)

func (x NodeState) Enum() *NodeState {
	p := new(NodeState)
	*p = x
	return p
}

func (x NodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_graph_node_proto_enumTypes[0].Descriptor()
}

func (NodeState) Type() protoreflect.EnumType {
	return &file_graph_node_proto_enumTypes[0]
}

func (x NodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeState.Descriptor instead.
func (NodeState) EnumDescriptor() ([]byte, []int) {
	return file_graph_node_proto_rawDescGZIP(), []int{0}
}

var File_graph_node_proto protoreflect.FileDescriptor

const file_graph_node_proto_rawDesc = "" +
	"\n" +
	"\x10graph/node.proto\x12\x03api*L\n" +
	"\tNodeState\x12\v\n" +
	"\aWaiting\x10\x00\x12\v\n" +
	"\aRunning\x10\x01\x12\f\n" +
	"\bFinished\x10\x02\x12\n" +
	"\n" +
	"\x06Failed\x10\x03\x12\v\n" +
	"\aStopped\x10\x04B\x11Z\x0fpipegraph/graphb\x06proto3"

var (
	file_graph_node_proto_rawDescOnce sync.Once
	file_graph_node_proto_rawDescData []byte
)

func file_graph_node_proto_rawDescGZIP() []byte {
	file_graph_node_proto_rawDescOnce.Do(func() {
		file_graph_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_node_proto_rawDesc), len(file_graph_node_proto_rawDesc)))
	})
	return file_graph_node_proto_rawDescData
}

var file_graph_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_graph_node_proto_goTypes = []any{
	(NodeState)(0), // 0: api.NodeState
}
var file_graph_node_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_graph_node_proto_init() }
func file_graph_node_proto_init() {
	if File_graph_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_node_proto_rawDesc), len(file_graph_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_graph_node_proto_goTypes,
		DependencyIndexes: file_graph_node_proto_depIdxs,
		EnumInfos:         file_graph_node_proto_enumTypes,
	}.Build()
	File_graph_node_proto = out.File
	file_graph_node_proto_goTypes = nil
	file_graph_node_proto_depIdxs = nil
}
