// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: graph.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobType int32

const (
	JobType_ShellScript JobType = 0
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "ShellScript",
	}
	JobType_value = map[string]int32{
		"ShellScript": 0,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_graph_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_graph_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{0}
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *JobType               `protobuf:"varint,1,opt,name=Type,proto3,enum=config.JobType,oneof" json:"Type,omitempty"`
	Path          *string                `protobuf:"bytes,2,opt,name=Path,proto3,oneof" json:"Path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetType() JobType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return JobType_ShellScript
}

func (x *Job) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

type Graph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,2,rep,name=Edges,proto3" json:"Edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Graph) Reset() {
	*x = Graph{}
	mi := &file_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Graph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graph) ProtoMessage() {}

func (x *Graph) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graph.ProtoReflect.Descriptor instead.
func (*Graph) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{1}
}

func (x *Graph) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Graph) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=Id,proto3,oneof" json:"Id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=Name,proto3,oneof" json:"Name,omitempty"`
	Job           *Job                   `protobuf:"bytes,3,opt,name=Job,proto3,oneof" json:"Job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Node) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Node) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    *uint64                `protobuf:"varint,1,opt,name=FromNodeId,proto3,oneof" json:"FromNodeId,omitempty"`
	ToNodeId      *uint64                `protobuf:"varint,2,opt,name=ToNodeId,proto3,oneof" json:"ToNodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{3}
}

func (x *Edge) GetFromNodeId() uint64 {
	if x != nil && x.FromNodeId != nil {
		return *x.FromNodeId
	}
	return 0
}

func (x *Edge) GetToNodeId() uint64 {
	if x != nil && x.ToNodeId != nil {
		return *x.ToNodeId
	}
	return 0
}

var File_graph_proto protoreflect.FileDescriptor

const file_graph_proto_rawDesc = "" +
	"\n" +
	"\vgraph.proto\x12\x06config\"Z\n" +
	"\x03Job\x12(\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x0f.config.JobTypeH\x00R\x04Type\x88\x01\x01\x12\x17\n" +
	"\x04Path\x18\x02 \x01(\tH\x01R\x04Path\x88\x01\x01B\a\n" +
	"\x05_TypeB\a\n" +
	"\x05_Path\"O\n" +
	"\x05Graph\x12\"\n" +
	"\x05Nodes\x18\x01 \x03(\v2\f.config.NodeR\x05Nodes\x12\"\n" +
	"\x05Edges\x18\x02 \x03(\v2\f.config.EdgeR\x05Edges\"p\n" +
	"\x04Node\x12\x13\n" +
	"\x02Id\x18\x01 \x01(\x04H\x00R\x02Id\x88\x01\x01\x12\x17\n" +
	"\x04Name\x18\x02 \x01(\tH\x01R\x04Name\x88\x01\x01\x12\"\n" +
	"\x03Job\x18\x03 \x01(\v2\v.config.JobH\x02R\x03Job\x88\x01\x01B\x05\n" +
	"\x03_IdB\a\n" +
	"\x05_NameB\x06\n" +
	"\x04_Job\"h\n" +
	"\x04Edge\x12#\n" +
	"\n" +
	"FromNodeId\x18\x01 \x01(\x04H\x00R\n" +
	"FromNodeId\x88\x01\x01\x12\x1f\n" +
	"\bToNodeId\x18\x02 \x01(\x04H\x01R\bToNodeId\x88\x01\x01B\r\n" +
	"\v_FromNodeIdB\v\n" +
	"\t_ToNodeId*\x1a\n" +
	"\aJobType\x12\x0f\n" +
	"\vShellScript\x10\x00B\vZ\t../configb\x06proto3"

var (
	file_graph_proto_rawDescOnce sync.Once
	file_graph_proto_rawDescData []byte
)

func file_graph_proto_rawDescGZIP() []byte {
	file_graph_proto_rawDescOnce.Do(func() {
		file_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)))
	})
	return file_graph_proto_rawDescData
}

var file_graph_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_graph_proto_goTypes = []any{
	(JobType)(0),  // 0: config.JobType
	(*Job)(nil),   // 1: config.Job
	(*Graph)(nil), // 2: config.Graph
	(*Node)(nil),  // 3: config.Node
	(*Edge)(nil),  // 4: config.Edge
}
var file_graph_proto_depIdxs = []int32{
	0, // 0: config.Job.Type:type_name -> config.JobType
	3, // 1: config.Graph.Nodes:type_name -> config.Node
	4, // 2: config.Graph.Edges:type_name -> config.Edge
	1, // 3: config.Node.Job:type_name -> config.Job
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_graph_proto_init() }
func file_graph_proto_init() {
	if File_graph_proto != nil {
		return
	}
	file_graph_proto_msgTypes[0].OneofWrappers = []any{}
	file_graph_proto_msgTypes[2].OneofWrappers = []any{}
	file_graph_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_graph_proto_goTypes,
		DependencyIndexes: file_graph_proto_depIdxs,
		EnumInfos:         file_graph_proto_enumTypes,
		MessageInfos:      file_graph_proto_msgTypes,
	}.Build()
	File_graph_proto = out.File
	file_graph_proto_goTypes = nil
	file_graph_proto_depIdxs = nil
}
