// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: job/register/shell.proto

package register

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShellScriptConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,opt,name=Path,proto3,oneof" json:"Path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellScriptConfig) Reset() {
	*x = ShellScriptConfig{}
	mi := &file_job_register_shell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellScriptConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellScriptConfig) ProtoMessage() {}

func (x *ShellScriptConfig) ProtoReflect() protoreflect.Message {
	mi := &file_job_register_shell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellScriptConfig.ProtoReflect.Descriptor instead.
func (*ShellScriptConfig) Descriptor() ([]byte, []int) {
	return file_job_register_shell_proto_rawDescGZIP(), []int{0}
}

func (x *ShellScriptConfig) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

var File_job_register_shell_proto protoreflect.FileDescriptor

const file_job_register_shell_proto_rawDesc = "" +
	"\n" +
	"\x18job/register/shell.proto\x12\bregister\"5\n" +
	"\x11ShellScriptConfig\x12\x17\n" +
	"\x04Path\x18\x01 \x01(\tH\x00R\x04Path\x88\x01\x01B\a\n" +
	"\x05_PathB\x14Z\x12pipegraph/registerb\x06proto3"

var (
	file_job_register_shell_proto_rawDescOnce sync.Once
	file_job_register_shell_proto_rawDescData []byte
)

func file_job_register_shell_proto_rawDescGZIP() []byte {
	file_job_register_shell_proto_rawDescOnce.Do(func() {
		file_job_register_shell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_register_shell_proto_rawDesc), len(file_job_register_shell_proto_rawDesc)))
	})
	return file_job_register_shell_proto_rawDescData
}

var file_job_register_shell_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_job_register_shell_proto_goTypes = []any{
	(*ShellScriptConfig)(nil), // 0: register.ShellScriptConfig
}
var file_job_register_shell_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_job_register_shell_proto_init() }
func file_job_register_shell_proto_init() {
	if File_job_register_shell_proto != nil {
		return
	}
	file_job_register_shell_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_register_shell_proto_rawDesc), len(file_job_register_shell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_job_register_shell_proto_goTypes,
		DependencyIndexes: file_job_register_shell_proto_depIdxs,
		MessageInfos:      file_job_register_shell_proto_msgTypes,
	}.Build()
	File_job_register_shell_proto = out.File
	file_job_register_shell_proto_goTypes = nil
	file_job_register_shell_proto_depIdxs = nil
}
