// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/job/register/shell.proto

package register

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShellScriptConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,req,name=Path" json:"Path,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=Args" json:"Args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellScriptConfig) Reset() {
	*x = ShellScriptConfig{}
	mi := &file_internal_job_register_shell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellScriptConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellScriptConfig) ProtoMessage() {}

func (x *ShellScriptConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_job_register_shell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellScriptConfig.ProtoReflect.Descriptor instead.
func (*ShellScriptConfig) Descriptor() ([]byte, []int) {
	return file_internal_job_register_shell_proto_rawDescGZIP(), []int{0}
}

func (x *ShellScriptConfig) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *ShellScriptConfig) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ShellCommandConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *string                `protobuf:"bytes,1,opt,name=Command" json:"Command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellCommandConfig) Reset() {
	*x = ShellCommandConfig{}
	mi := &file_internal_job_register_shell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellCommandConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellCommandConfig) ProtoMessage() {}

func (x *ShellCommandConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_job_register_shell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellCommandConfig.ProtoReflect.Descriptor instead.
func (*ShellCommandConfig) Descriptor() ([]byte, []int) {
	return file_internal_job_register_shell_proto_rawDescGZIP(), []int{1}
}

func (x *ShellCommandConfig) GetCommand() string {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return ""
}

var File_internal_job_register_shell_proto protoreflect.FileDescriptor

const file_internal_job_register_shell_proto_rawDesc = "" +
	"\n" +
	"!internal/job/register/shell.proto\x12\bregister\";\n" +
	"\x11ShellScriptConfig\x12\x12\n" +
	"\x04Path\x18\x01 \x02(\tR\x04Path\x12\x12\n" +
	"\x04Args\x18\x02 \x03(\tR\x04Args\".\n" +
	"\x12ShellCommandConfig\x12\x18\n" +
	"\aCommand\x18\x01 \x01(\tR\aCommandB\x14Z\x12pipegraph/register"

var (
	file_internal_job_register_shell_proto_rawDescOnce sync.Once
	file_internal_job_register_shell_proto_rawDescData []byte
)

func file_internal_job_register_shell_proto_rawDescGZIP() []byte {
	file_internal_job_register_shell_proto_rawDescOnce.Do(func() {
		file_internal_job_register_shell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_job_register_shell_proto_rawDesc), len(file_internal_job_register_shell_proto_rawDesc)))
	})
	return file_internal_job_register_shell_proto_rawDescData
}

var file_internal_job_register_shell_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_job_register_shell_proto_goTypes = []any{
	(*ShellScriptConfig)(nil),  // 0: register.ShellScriptConfig
	(*ShellCommandConfig)(nil), // 1: register.ShellCommandConfig
}
var file_internal_job_register_shell_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_job_register_shell_proto_init() }
func file_internal_job_register_shell_proto_init() {
	if File_internal_job_register_shell_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_job_register_shell_proto_rawDesc), len(file_internal_job_register_shell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_job_register_shell_proto_goTypes,
		DependencyIndexes: file_internal_job_register_shell_proto_depIdxs,
		MessageInfos:      file_internal_job_register_shell_proto_msgTypes,
	}.Build()
	File_internal_job_register_shell_proto = out.File
	file_internal_job_register_shell_proto_goTypes = nil
	file_internal_job_register_shell_proto_depIdxs = nil
}
