// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/job/register/file/file.proto

package util

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []string               `protobuf:"bytes,1,rep,name=Data" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileConfig) Reset() {
	*x = FileConfig{}
	mi := &file_internal_job_register_file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileConfig) ProtoMessage() {}

func (x *FileConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_job_register_file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileConfig.ProtoReflect.Descriptor instead.
func (*FileConfig) Descriptor() ([]byte, []int) {
	return file_internal_job_register_file_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileConfig) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_job_register_file_file_proto protoreflect.FileDescriptor

const file_internal_job_register_file_file_proto_rawDesc = "" +
	"\n" +
	"%internal/job/register/file/file.proto\x12\bregister\" \n" +
	"\n" +
	"FileConfig\x12\x12\n" +
	"\x04Data\x18\x01 \x03(\tR\x04DataB\x10Z\x0epipegraph/util"

var (
	file_internal_job_register_file_file_proto_rawDescOnce sync.Once
	file_internal_job_register_file_file_proto_rawDescData []byte
)

func file_internal_job_register_file_file_proto_rawDescGZIP() []byte {
	file_internal_job_register_file_file_proto_rawDescOnce.Do(func() {
		file_internal_job_register_file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_job_register_file_file_proto_rawDesc), len(file_internal_job_register_file_file_proto_rawDesc)))
	})
	return file_internal_job_register_file_file_proto_rawDescData
}

var file_internal_job_register_file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_job_register_file_file_proto_goTypes = []any{
	(*FileConfig)(nil), // 0: register.FileConfig
}
var file_internal_job_register_file_file_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_job_register_file_file_proto_init() }
func file_internal_job_register_file_file_proto_init() {
	if File_internal_job_register_file_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_job_register_file_file_proto_rawDesc), len(file_internal_job_register_file_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_job_register_file_file_proto_goTypes,
		DependencyIndexes: file_internal_job_register_file_file_proto_depIdxs,
		MessageInfos:      file_internal_job_register_file_file_proto_msgTypes,
	}.Build()
	File_internal_job_register_file_file_proto = out.File
	file_internal_job_register_file_file_proto_goTypes = nil
	file_internal_job_register_file_file_proto_depIdxs = nil
}
