// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/job/register/daemon/daemon.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DaemonConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *string                `protobuf:"bytes,1,req,name=Run" json:"Run,omitempty"`
	Status        *string                `protobuf:"bytes,2,req,name=Status" json:"Status,omitempty"`
	Shutdown      *string                `protobuf:"bytes,3,req,name=Shutdown" json:"Shutdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonConfig) Reset() {
	*x = DaemonConfig{}
	mi := &file_internal_job_register_daemon_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonConfig) ProtoMessage() {}

func (x *DaemonConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_job_register_daemon_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonConfig.ProtoReflect.Descriptor instead.
func (*DaemonConfig) Descriptor() ([]byte, []int) {
	return file_internal_job_register_daemon_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *DaemonConfig) GetRun() string {
	if x != nil && x.Run != nil {
		return *x.Run
	}
	return ""
}

func (x *DaemonConfig) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *DaemonConfig) GetShutdown() string {
	if x != nil && x.Shutdown != nil {
		return *x.Shutdown
	}
	return ""
}

type DaemonMonitorConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonMonitorConfig) Reset() {
	*x = DaemonMonitorConfig{}
	mi := &file_internal_job_register_daemon_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonMonitorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonMonitorConfig) ProtoMessage() {}

func (x *DaemonMonitorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_job_register_daemon_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonMonitorConfig.ProtoReflect.Descriptor instead.
func (*DaemonMonitorConfig) Descriptor() ([]byte, []int) {
	return file_internal_job_register_daemon_daemon_proto_rawDescGZIP(), []int{1}
}

var File_internal_job_register_daemon_daemon_proto protoreflect.FileDescriptor

const file_internal_job_register_daemon_daemon_proto_rawDesc = "" +
	"\n" +
	")internal/job/register/daemon/daemon.proto\x12\bregister\"T\n" +
	"\fDaemonConfig\x12\x10\n" +
	"\x03Run\x18\x01 \x02(\tR\x03Run\x12\x16\n" +
	"\x06Status\x18\x02 \x02(\tR\x06Status\x12\x1a\n" +
	"\bShutdown\x18\x03 \x02(\tR\bShutdown\"\x15\n" +
	"\x13DaemonMonitorConfigB\x12Z\x10pipegraph/daemon"

var (
	file_internal_job_register_daemon_daemon_proto_rawDescOnce sync.Once
	file_internal_job_register_daemon_daemon_proto_rawDescData []byte
)

func file_internal_job_register_daemon_daemon_proto_rawDescGZIP() []byte {
	file_internal_job_register_daemon_daemon_proto_rawDescOnce.Do(func() {
		file_internal_job_register_daemon_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_job_register_daemon_daemon_proto_rawDesc), len(file_internal_job_register_daemon_daemon_proto_rawDesc)))
	})
	return file_internal_job_register_daemon_daemon_proto_rawDescData
}

var file_internal_job_register_daemon_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_job_register_daemon_daemon_proto_goTypes = []any{
	(*DaemonConfig)(nil),        // 0: register.DaemonConfig
	(*DaemonMonitorConfig)(nil), // 1: register.DaemonMonitorConfig
}
var file_internal_job_register_daemon_daemon_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_job_register_daemon_daemon_proto_init() }
func file_internal_job_register_daemon_daemon_proto_init() {
	if File_internal_job_register_daemon_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_job_register_daemon_daemon_proto_rawDesc), len(file_internal_job_register_daemon_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_job_register_daemon_daemon_proto_goTypes,
		DependencyIndexes: file_internal_job_register_daemon_daemon_proto_depIdxs,
		MessageInfos:      file_internal_job_register_daemon_daemon_proto_msgTypes,
	}.Build()
	File_internal_job_register_daemon_daemon_proto = out.File
	file_internal_job_register_daemon_daemon_proto_goTypes = nil
	file_internal_job_register_daemon_daemon_proto_depIdxs = nil
}
