// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/graph/config.proto

package graph

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncType int32

const (
	SyncType_InitNode    SyncType = 1
	SyncType_InitEdge    SyncType = 2
	SyncType_InitDone    SyncType = 3
	SyncType_UpdateState SyncType = 4
	SyncType_Reset       SyncType = 5
)

// Enum value maps for SyncType.
var (
	SyncType_name = map[int32]string{
		1: "InitNode",
		2: "InitEdge",
		3: "InitDone",
		4: "UpdateState",
		5: "Reset",
	}
	SyncType_value = map[string]int32{
		"InitNode":    1,
		"InitEdge":    2,
		"InitDone":    3,
		"UpdateState": 4,
		"Reset":       5,
	}
)

func (x SyncType) Enum() *SyncType {
	p := new(SyncType)
	*p = x
	return p
}

func (x SyncType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_graph_config_proto_enumTypes[0].Descriptor()
}

func (SyncType) Type() protoreflect.EnumType {
	return &file_internal_graph_config_proto_enumTypes[0]
}

func (x SyncType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SyncType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SyncType(num)
	return nil
}

// Deprecated: Use SyncType.Descriptor instead.
func (SyncType) EnumDescriptor() ([]byte, []int) {
	return file_internal_graph_config_proto_rawDescGZIP(), []int{0}
}

type NodeState_IdleState_IdlePlan int32

const (
	NodeState_IdleState_None      NodeState_IdleState_IdlePlan = 0
	NodeState_IdleState_Scheduled NodeState_IdleState_IdlePlan = 1
	NodeState_IdleState_Skipped   NodeState_IdleState_IdlePlan = 2
)

// Enum value maps for NodeState_IdleState_IdlePlan.
var (
	NodeState_IdleState_IdlePlan_name = map[int32]string{
		0: "None",
		1: "Scheduled",
		2: "Skipped",
	}
	NodeState_IdleState_IdlePlan_value = map[string]int32{
		"None":      0,
		"Scheduled": 1,
		"Skipped":   2,
	}
)

func (x NodeState_IdleState_IdlePlan) Enum() *NodeState_IdleState_IdlePlan {
	p := new(NodeState_IdleState_IdlePlan)
	*p = x
	return p
}

func (x NodeState_IdleState_IdlePlan) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState_IdleState_IdlePlan) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_graph_config_proto_enumTypes[1].Descriptor()
}

func (NodeState_IdleState_IdlePlan) Type() protoreflect.EnumType {
	return &file_internal_graph_config_proto_enumTypes[1]
}

func (x NodeState_IdleState_IdlePlan) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *NodeState_IdleState_IdlePlan) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = NodeState_IdleState_IdlePlan(num)
	return nil
}

// Deprecated: Use NodeState_IdleState_IdlePlan.Descriptor instead.
func (NodeState_IdleState_IdlePlan) EnumDescriptor() ([]byte, []int) {
	return file_internal_graph_config_proto_rawDescGZIP(), []int{0, 0, 0}
}

type NodeState_InProgressState_InProgressStatus int32

const (
	NodeState_InProgressState_Scheduled NodeState_InProgressState_InProgressStatus = 0 // NotImplemented
	NodeState_InProgressState_Running   NodeState_InProgressState_InProgressStatus = 1
	NodeState_InProgressState_Stopping  NodeState_InProgressState_InProgressStatus = 2
	NodeState_InProgressState_Skipping  NodeState_InProgressState_InProgressStatus = 3
)

// Enum value maps for NodeState_InProgressState_InProgressStatus.
var (
	NodeState_InProgressState_InProgressStatus_name = map[int32]string{
		0: "Scheduled",
		1: "Running",
		2: "Stopping",
		3: "Skipping",
	}
	NodeState_InProgressState_InProgressStatus_value = map[string]int32{
		"Scheduled": 0,
		"Running":   1,
		"Stopping":  2,
		"Skipping":  3,
	}
)

func (x NodeState_InProgressState_InProgressStatus) Enum() *NodeState_InProgressState_InProgressStatus {
	p := new(NodeState_InProgressState_InProgressStatus)
	*p = x
	return p
}

func (x NodeState_InProgressState_InProgressStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState_InProgressState_InProgressStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_graph_config_proto_enumTypes[2].Descriptor()
}

func (NodeState_InProgressState_InProgressStatus) Type() protoreflect.EnumType {
	return &file_internal_graph_config_proto_enumTypes[2]
}

func (x NodeState_InProgressState_InProgressStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *NodeState_InProgressState_InProgressStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = NodeState_InProgressState_InProgressStatus(num)
	return nil
}

// Deprecated: Use NodeState_InProgressState_InProgressStatus.Descriptor instead.
func (NodeState_InProgressState_InProgressStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_graph_config_proto_rawDescGZIP(), []int{0, 1, 0}
}

type NodeState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *uint64                `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	// Types that are valid to be assigned to State:
	//
	//	*NodeState_Idle
	//	*NodeState_InProgress
	//	*NodeState_Done
	State         isNodeState_State `protobuf_oneof:"State"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeState) Reset() {
	*x = NodeState{}
	mi := &file_internal_graph_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState) ProtoMessage() {}

func (x *NodeState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_graph_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState.ProtoReflect.Descriptor instead.
func (*NodeState) Descriptor() ([]byte, []int) {
	return file_internal_graph_config_proto_rawDescGZIP(), []int{0}
}

func (x *NodeState) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *NodeState) GetState() isNodeState_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *NodeState) GetIdle() *NodeState_IdleState {
	if x != nil {
		if x, ok := x.State.(*NodeState_Idle); ok {
			return x.Idle
		}
	}
	return nil
}

func (x *NodeState) GetInProgress() *NodeState_InProgressState {
	if x != nil {
		if x, ok := x.State.(*NodeState_InProgress); ok {
			return x.InProgress
		}
	}
	return nil
}

func (x *NodeState) GetDone() *NodeState_DoneState {
	if x != nil {
		if x, ok := x.State.(*NodeState_Done); ok {
			return x.Done
		}
	}
	return nil
}

type isNodeState_State interface {
	isNodeState_State()
}

type NodeState_Idle struct {
	Idle *NodeState_IdleState `protobuf:"bytes,2,opt,name=Idle,oneof"`
}

type NodeState_InProgress struct {
	InProgress *NodeState_InProgressState `protobuf:"bytes,3,opt,name=InProgress,oneof"`
}

type NodeState_Done struct {
	Done *NodeState_DoneState `protobuf:"bytes,4,opt,name=Done,oneof"`
}

func (*NodeState_Idle) isNodeState_State() {}

func (*NodeState_InProgress) isNodeState_State() {}

func (*NodeState_Done) isNodeState_State() {}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeConfig          `protobuf:"bytes,1,rep,name=Nodes" json:"Nodes,omitempty"`
	Edges         []*EdgeConfig          `protobuf:"bytes,2,rep,name=Edges" json:"Edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_internal_graph_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_internal_graph_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_internal_graph_config_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetNodes() []*NodeConfig {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Config) GetEdges() []*EdgeConfig {
	if x != nil {
		return x.Edges
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *int32                 `protobuf:"varint,1,opt,name=X" json:"X,omitempty"`
	Y             *int32                 `protobuf:"varint,2,opt,name=Y" json:"Y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_internal_graph_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_internal_graph_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_internal_graph_config_proto_rawDescGZIP(), []int{2}
}

func (x *Position) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type NodeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Job           *any1.Any              `protobuf:"bytes,3,opt,name=Job" json:"Job,omitempty"`
	Position      *Position              `protobuf:"bytes,4,opt,name=Position" json:"Position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_internal_graph_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_graph_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_internal_graph_config_proto_rawDescGZIP(), []int{3}
}

func (x *NodeConfig) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *NodeConfig) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *NodeConfig) GetJob() *any1.Any {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *NodeConfig) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type EdgeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    *uint64                `protobuf:"varint,1,opt,name=FromNodeId" json:"FromNodeId,omitempty"`
	ToNodeId      *uint64                `protobuf:"varint,2,opt,name=ToNodeId" json:"ToNodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeConfig) Reset() {
	*x = EdgeConfig{}
	mi := &file_internal_graph_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeConfig) ProtoMessage() {}

func (x *EdgeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_graph_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeConfig.ProtoReflect.Descriptor instead.
func (*EdgeConfig) Descriptor() ([]byte, []int) {
	return file_internal_graph_config_proto_rawDescGZIP(), []int{4}
}

func (x *EdgeConfig) GetFromNodeId() uint64 {
	if x != nil && x.FromNodeId != nil {
		return *x.FromNodeId
	}
	return 0
}

func (x *EdgeConfig) GetToNodeId() uint64 {
	if x != nil && x.ToNodeId != nil {
		return *x.ToNodeId
	}
	return 0
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *SyncType              `protobuf:"varint,1,opt,name=Type,enum=graph.SyncType" json:"Type,omitempty"`
	NodeConfig    *NodeConfig            `protobuf:"bytes,2,opt,name=NodeConfig" json:"NodeConfig,omitempty"`
	NodeState     *NodeState             `protobuf:"bytes,3,opt,name=NodeState" json:"NodeState,omitempty"`
	EdgeConfig    *EdgeConfig            `protobuf:"bytes,4,opt,name=EdgeConfig" json:"EdgeConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_internal_graph_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_graph_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_internal_graph_config_proto_rawDescGZIP(), []int{5}
}

func (x *SyncResponse) GetType() SyncType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return SyncType_InitNode
}

func (x *SyncResponse) GetNodeConfig() *NodeConfig {
	if x != nil {
		return x.NodeConfig
	}
	return nil
}

func (x *SyncResponse) GetNodeState() *NodeState {
	if x != nil {
		return x.NodeState
	}
	return nil
}

func (x *SyncResponse) GetEdgeConfig() *EdgeConfig {
	if x != nil {
		return x.EdgeConfig
	}
	return nil
}

type NodeState_IdleState struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	IsReady       *bool                         `protobuf:"varint,1,opt,name=IsReady" json:"IsReady,omitempty"`
	Plan          *NodeState_IdleState_IdlePlan `protobuf:"varint,2,opt,name=Plan,enum=graph.NodeState_IdleState_IdlePlan" json:"Plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeState_IdleState) Reset() {
	*x = NodeState_IdleState{}
	mi := &file_internal_graph_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState_IdleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState_IdleState) ProtoMessage() {}

func (x *NodeState_IdleState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_graph_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState_IdleState.ProtoReflect.Descriptor instead.
func (*NodeState_IdleState) Descriptor() ([]byte, []int) {
	return file_internal_graph_config_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NodeState_IdleState) GetIsReady() bool {
	if x != nil && x.IsReady != nil {
		return *x.IsReady
	}
	return false
}

func (x *NodeState_IdleState) GetPlan() NodeState_IdleState_IdlePlan {
	if x != nil && x.Plan != nil {
		return *x.Plan
	}
	return NodeState_IdleState_None
}

type NodeState_InProgressState struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	Status        *NodeState_InProgressState_InProgressStatus `protobuf:"varint,1,opt,name=Status,enum=graph.NodeState_InProgressState_InProgressStatus" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeState_InProgressState) Reset() {
	*x = NodeState_InProgressState{}
	mi := &file_internal_graph_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState_InProgressState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState_InProgressState) ProtoMessage() {}

func (x *NodeState_InProgressState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_graph_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState_InProgressState.ProtoReflect.Descriptor instead.
func (*NodeState_InProgressState) Descriptor() ([]byte, []int) {
	return file_internal_graph_config_proto_rawDescGZIP(), []int{0, 1}
}

func (x *NodeState_InProgressState) GetStatus() NodeState_InProgressState_InProgressStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return NodeState_InProgressState_Scheduled
}

type NodeState_DoneState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=Error" json:"Error,omitempty"`
	IsStopped     *bool                  `protobuf:"varint,3,req,name=IsStopped" json:"IsStopped,omitempty"`
	IsSkipped     *bool                  `protobuf:"varint,4,req,name=IsSkipped" json:"IsSkipped,omitempty"`
	FromIdle      *bool                  `protobuf:"varint,5,opt,name=FromIdle" json:"FromIdle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeState_DoneState) Reset() {
	*x = NodeState_DoneState{}
	mi := &file_internal_graph_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState_DoneState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState_DoneState) ProtoMessage() {}

func (x *NodeState_DoneState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_graph_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState_DoneState.ProtoReflect.Descriptor instead.
func (*NodeState_DoneState) Descriptor() ([]byte, []int) {
	return file_internal_graph_config_proto_rawDescGZIP(), []int{0, 2}
}

func (x *NodeState_DoneState) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *NodeState_DoneState) GetIsStopped() bool {
	if x != nil && x.IsStopped != nil {
		return *x.IsStopped
	}
	return false
}

func (x *NodeState_DoneState) GetIsSkipped() bool {
	if x != nil && x.IsSkipped != nil {
		return *x.IsSkipped
	}
	return false
}

func (x *NodeState_DoneState) GetFromIdle() bool {
	if x != nil && x.FromIdle != nil {
		return *x.FromIdle
	}
	return false
}

var File_internal_graph_config_proto protoreflect.FileDescriptor

const file_internal_graph_config_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/graph/config.proto\x12\x05graph\x1a\x19google/protobuf/any.proto\"\x85\x05\n" +
	"\tNodeState\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x120\n" +
	"\x04Idle\x18\x02 \x01(\v2\x1a.graph.NodeState.IdleStateH\x00R\x04Idle\x12B\n" +
	"\n" +
	"InProgress\x18\x03 \x01(\v2 .graph.NodeState.InProgressStateH\x00R\n" +
	"InProgress\x120\n" +
	"\x04Done\x18\x04 \x01(\v2\x1a.graph.NodeState.DoneStateH\x00R\x04Done\x1a\x90\x01\n" +
	"\tIdleState\x12\x18\n" +
	"\aIsReady\x18\x01 \x01(\bR\aIsReady\x127\n" +
	"\x04Plan\x18\x02 \x01(\x0e2#.graph.NodeState.IdleState.IdlePlanR\x04Plan\"0\n" +
	"\bIdlePlan\x12\b\n" +
	"\x04None\x10\x00\x12\r\n" +
	"\tScheduled\x10\x01\x12\v\n" +
	"\aSkipped\x10\x02\x1a\xa8\x01\n" +
	"\x0fInProgressState\x12I\n" +
	"\x06Status\x18\x01 \x01(\x0e21.graph.NodeState.InProgressState.InProgressStatusR\x06Status\"J\n" +
	"\x10InProgressStatus\x12\r\n" +
	"\tScheduled\x10\x00\x12\v\n" +
	"\aRunning\x10\x01\x12\f\n" +
	"\bStopping\x10\x02\x12\f\n" +
	"\bSkipping\x10\x03\x1ay\n" +
	"\tDoneState\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05Error\x12\x1c\n" +
	"\tIsStopped\x18\x03 \x02(\bR\tIsStopped\x12\x1c\n" +
	"\tIsSkipped\x18\x04 \x02(\bR\tIsSkipped\x12\x1a\n" +
	"\bFromIdle\x18\x05 \x01(\bR\bFromIdleB\a\n" +
	"\x05State\"Z\n" +
	"\x06Config\x12'\n" +
	"\x05Nodes\x18\x01 \x03(\v2\x11.graph.NodeConfigR\x05Nodes\x12'\n" +
	"\x05Edges\x18\x02 \x03(\v2\x11.graph.EdgeConfigR\x05Edges\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01X\x18\x01 \x01(\x05R\x01X\x12\f\n" +
	"\x01Y\x18\x02 \x01(\x05R\x01Y\"\x85\x01\n" +
	"\n" +
	"NodeConfig\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12&\n" +
	"\x03Job\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x03Job\x12+\n" +
	"\bPosition\x18\x04 \x01(\v2\x0f.graph.PositionR\bPosition\"H\n" +
	"\n" +
	"EdgeConfig\x12\x1e\n" +
	"\n" +
	"FromNodeId\x18\x01 \x01(\x04R\n" +
	"FromNodeId\x12\x1a\n" +
	"\bToNodeId\x18\x02 \x01(\x04R\bToNodeId\"\xc9\x01\n" +
	"\fSyncResponse\x12#\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x0f.graph.SyncTypeR\x04Type\x121\n" +
	"\n" +
	"NodeConfig\x18\x02 \x01(\v2\x11.graph.NodeConfigR\n" +
	"NodeConfig\x12.\n" +
	"\tNodeState\x18\x03 \x01(\v2\x10.graph.NodeStateR\tNodeState\x121\n" +
	"\n" +
	"EdgeConfig\x18\x04 \x01(\v2\x11.graph.EdgeConfigR\n" +
	"EdgeConfig*P\n" +
	"\bSyncType\x12\f\n" +
	"\bInitNode\x10\x01\x12\f\n" +
	"\bInitEdge\x10\x02\x12\f\n" +
	"\bInitDone\x10\x03\x12\x0f\n" +
	"\vUpdateState\x10\x04\x12\t\n" +
	"\x05Reset\x10\x05B\x1aZ\x18pipegraph/internal/graph"

var (
	file_internal_graph_config_proto_rawDescOnce sync.Once
	file_internal_graph_config_proto_rawDescData []byte
)

func file_internal_graph_config_proto_rawDescGZIP() []byte {
	file_internal_graph_config_proto_rawDescOnce.Do(func() {
		file_internal_graph_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_graph_config_proto_rawDesc), len(file_internal_graph_config_proto_rawDesc)))
	})
	return file_internal_graph_config_proto_rawDescData
}

var file_internal_graph_config_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_graph_config_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_graph_config_proto_goTypes = []any{
	(SyncType)(0),                                   // 0: graph.SyncType
	(NodeState_IdleState_IdlePlan)(0),               // 1: graph.NodeState.IdleState.IdlePlan
	(NodeState_InProgressState_InProgressStatus)(0), // 2: graph.NodeState.InProgressState.InProgressStatus
	(*NodeState)(nil),                               // 3: graph.NodeState
	(*Config)(nil),                                  // 4: graph.Config
	(*Position)(nil),                                // 5: graph.Position
	(*NodeConfig)(nil),                              // 6: graph.NodeConfig
	(*EdgeConfig)(nil),                              // 7: graph.EdgeConfig
	(*SyncResponse)(nil),                            // 8: graph.SyncResponse
	(*NodeState_IdleState)(nil),                     // 9: graph.NodeState.IdleState
	(*NodeState_InProgressState)(nil),               // 10: graph.NodeState.InProgressState
	(*NodeState_DoneState)(nil),                     // 11: graph.NodeState.DoneState
	(*any1.Any)(nil),                                // 12: google.protobuf.Any
}
var file_internal_graph_config_proto_depIdxs = []int32{
	9,  // 0: graph.NodeState.Idle:type_name -> graph.NodeState.IdleState
	10, // 1: graph.NodeState.InProgress:type_name -> graph.NodeState.InProgressState
	11, // 2: graph.NodeState.Done:type_name -> graph.NodeState.DoneState
	6,  // 3: graph.Config.Nodes:type_name -> graph.NodeConfig
	7,  // 4: graph.Config.Edges:type_name -> graph.EdgeConfig
	12, // 5: graph.NodeConfig.Job:type_name -> google.protobuf.Any
	5,  // 6: graph.NodeConfig.Position:type_name -> graph.Position
	0,  // 7: graph.SyncResponse.Type:type_name -> graph.SyncType
	6,  // 8: graph.SyncResponse.NodeConfig:type_name -> graph.NodeConfig
	3,  // 9: graph.SyncResponse.NodeState:type_name -> graph.NodeState
	7,  // 10: graph.SyncResponse.EdgeConfig:type_name -> graph.EdgeConfig
	1,  // 11: graph.NodeState.IdleState.Plan:type_name -> graph.NodeState.IdleState.IdlePlan
	2,  // 12: graph.NodeState.InProgressState.Status:type_name -> graph.NodeState.InProgressState.InProgressStatus
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_graph_config_proto_init() }
func file_internal_graph_config_proto_init() {
	if File_internal_graph_config_proto != nil {
		return
	}
	file_internal_graph_config_proto_msgTypes[0].OneofWrappers = []any{
		(*NodeState_Idle)(nil),
		(*NodeState_InProgress)(nil),
		(*NodeState_Done)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_graph_config_proto_rawDesc), len(file_internal_graph_config_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_graph_config_proto_goTypes,
		DependencyIndexes: file_internal_graph_config_proto_depIdxs,
		EnumInfos:         file_internal_graph_config_proto_enumTypes,
		MessageInfos:      file_internal_graph_config_proto_msgTypes,
	}.Build()
	File_internal_graph_config_proto = out.File
	file_internal_graph_config_proto_goTypes = nil
	file_internal_graph_config_proto_depIdxs = nil
}
