// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/job/job.proto

package job

import (
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldInputType int32

const (
	FieldInputType_Auto       FieldInputType = 0
	FieldInputType_Input      FieldInputType = 1
	FieldInputType_TextArea   FieldInputType = 2
	FieldInputType_CodeEditor FieldInputType = 3
)

// Enum value maps for FieldInputType.
var (
	FieldInputType_name = map[int32]string{
		0: "Auto",
		1: "Input",
		2: "TextArea",
		3: "CodeEditor",
	}
	FieldInputType_value = map[string]int32{
		"Auto":       0,
		"Input":      1,
		"TextArea":   2,
		"CodeEditor": 3,
	}
)

func (x FieldInputType) Enum() *FieldInputType {
	p := new(FieldInputType)
	*p = x
	return p
}

func (x FieldInputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldInputType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_job_job_proto_enumTypes[0].Descriptor()
}

func (FieldInputType) Type() protoreflect.EnumType {
	return &file_internal_job_job_proto_enumTypes[0]
}

func (x FieldInputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FieldInputType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FieldInputType(num)
	return nil
}

// Deprecated: Use FieldInputType.Descriptor instead.
func (FieldInputType) EnumDescriptor() ([]byte, []int) {
	return file_internal_job_job_proto_rawDescGZIP(), []int{0}
}

var file_internal_job_job_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*FieldInputType)(nil),
		Field:         50000,
		Name:          "job.InputType",
		Tag:           "varint,50000,opt,name=InputType,enum=job.FieldInputType",
		Filename:      "internal/job/job.proto",
	},
}

// Extension fields to descriptor.FieldOptions.
var (
	// optional job.FieldInputType InputType = 50000;
	E_InputType = &file_internal_job_job_proto_extTypes[0]
)

var File_internal_job_job_proto protoreflect.FileDescriptor

const file_internal_job_job_proto_rawDesc = "" +
	"\n" +
	"\x16internal/job/job.proto\x12\x03job\x1a google/protobuf/descriptor.proto*C\n" +
	"\x0eFieldInputType\x12\b\n" +
	"\x04Auto\x10\x00\x12\t\n" +
	"\x05Input\x10\x01\x12\f\n" +
	"\bTextArea\x10\x02\x12\x0e\n" +
	"\n" +
	"CodeEditor\x10\x03:R\n" +
	"\tInputType\x12\x1d.google.protobuf.FieldOptions\x18І\x03 \x01(\x0e2\x13.job.FieldInputTypeR\tInputTypeB\x13Z\x11yarl/internal/job"

var (
	file_internal_job_job_proto_rawDescOnce sync.Once
	file_internal_job_job_proto_rawDescData []byte
)

func file_internal_job_job_proto_rawDescGZIP() []byte {
	file_internal_job_job_proto_rawDescOnce.Do(func() {
		file_internal_job_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_job_job_proto_rawDesc), len(file_internal_job_job_proto_rawDesc)))
	})
	return file_internal_job_job_proto_rawDescData
}

var file_internal_job_job_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_job_job_proto_goTypes = []any{
	(FieldInputType)(0),             // 0: job.FieldInputType
	(*descriptor.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_internal_job_job_proto_depIdxs = []int32{
	1, // 0: job.InputType:extendee -> google.protobuf.FieldOptions
	0, // 1: job.InputType:type_name -> job.FieldInputType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_job_job_proto_init() }
func file_internal_job_job_proto_init() {
	if File_internal_job_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_job_job_proto_rawDesc), len(file_internal_job_job_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_internal_job_job_proto_goTypes,
		DependencyIndexes: file_internal_job_job_proto_depIdxs,
		EnumInfos:         file_internal_job_job_proto_enumTypes,
		ExtensionInfos:    file_internal_job_job_proto_extTypes,
	}.Build()
	File_internal_job_job_proto = out.File
	file_internal_job_job_proto_goTypes = nil
	file_internal_job_job_proto_depIdxs = nil
}
