// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	graph "pipegraph/graph"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nothing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nothing) Reset() {
	*x = Nothing{}
	mi := &file_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nothing) ProtoMessage() {}

func (x *Nothing) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nothing.ProtoReflect.Descriptor instead.
func (*Nothing) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

type GraphState struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	NodeStates    map[uint64]graph.NodeState `protobuf:"bytes,1,rep,name=NodeStates,proto3" json:"NodeStates,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=graph.NodeState"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphState) Reset() {
	*x = GraphState{}
	mi := &file_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphState) ProtoMessage() {}

func (x *GraphState) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphState.ProtoReflect.Descriptor instead.
func (*GraphState) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *GraphState) GetNodeStates() map[uint64]graph.NodeState {
	if x != nil {
		return x.NodeStates
	}
	return nil
}

type NodeIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=Id,proto3,oneof" json:"Id,omitempty"` // optional string Name = 2;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIdentifier) Reset() {
	*x = NodeIdentifier{}
	mi := &file_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdentifier) ProtoMessage() {}

func (x *NodeIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdentifier.ProtoReflect.Descriptor instead.
func (*NodeIdentifier) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *NodeIdentifier) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type ArtifactsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        *string                `protobuf:"bytes,1,opt,name=Stdout,proto3,oneof" json:"Stdout,omitempty"`
	Stderr        *string                `protobuf:"bytes,2,opt,name=Stderr,proto3,oneof" json:"Stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactsMessage) Reset() {
	*x = ArtifactsMessage{}
	mi := &file_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactsMessage) ProtoMessage() {}

func (x *ArtifactsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactsMessage.ProtoReflect.Descriptor instead.
func (*ArtifactsMessage) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *ArtifactsMessage) GetStdout() string {
	if x != nil && x.Stdout != nil {
		return *x.Stdout
	}
	return ""
}

func (x *ArtifactsMessage) GetStderr() string {
	if x != nil && x.Stderr != nil {
		return *x.Stderr
	}
	return ""
}

var File_api_api_proto protoreflect.FileDescriptor

const file_api_api_proto_rawDesc = "" +
	"\n" +
	"\rapi/api.proto\x12\x03api\x1a\x12graph/config.proto\"\t\n" +
	"\aNothing\"\x9e\x01\n" +
	"\n" +
	"GraphState\x12?\n" +
	"\n" +
	"NodeStates\x18\x01 \x03(\v2\x1f.api.GraphState.NodeStatesEntryR\n" +
	"NodeStates\x1aO\n" +
	"\x0fNodeStatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\x0e2\x10.graph.NodeStateR\x05value:\x028\x01\",\n" +
	"\x0eNodeIdentifier\x12\x13\n" +
	"\x02Id\x18\x01 \x01(\x04H\x00R\x02Id\x88\x01\x01B\x05\n" +
	"\x03_Id\"b\n" +
	"\x10ArtifactsMessage\x12\x1b\n" +
	"\x06Stdout\x18\x01 \x01(\tH\x00R\x06Stdout\x88\x01\x01\x12\x1b\n" +
	"\x06Stderr\x18\x02 \x01(\tH\x01R\x06Stderr\x88\x01\x01B\t\n" +
	"\a_StdoutB\t\n" +
	"\a_Stderr2\x7f\n" +
	"\x05Graph\x12(\n" +
	"\tGetConfig\x12\f.api.Nothing\x1a\r.graph.Config\x12)\n" +
	"\bGetState\x12\f.api.Nothing\x1a\x0f.api.GraphState\x12!\n" +
	"\x03Run\x12\f.api.Nothing\x1a\f.api.Nothing2\x98\x01\n" +
	"\x04Node\x12(\n" +
	"\x03Run\x12\x13.api.NodeIdentifier\x1a\f.api.Nothing\x12*\n" +
	"\x05Reset\x12\x13.api.NodeIdentifier\x1a\f.api.Nothing\x12:\n" +
	"\fGetArtifacts\x12\x13.api.NodeIdentifier\x1a\x15.api.ArtifactsMessageB\x16Z\x14pipegraph/server/apib\x06proto3"

var (
	file_api_api_proto_rawDescOnce sync.Once
	file_api_api_proto_rawDescData []byte
)

func file_api_api_proto_rawDescGZIP() []byte {
	file_api_api_proto_rawDescOnce.Do(func() {
		file_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)))
	})
	return file_api_api_proto_rawDescData
}

var file_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_api_proto_goTypes = []any{
	(*Nothing)(nil),          // 0: api.Nothing
	(*GraphState)(nil),       // 1: api.GraphState
	(*NodeIdentifier)(nil),   // 2: api.NodeIdentifier
	(*ArtifactsMessage)(nil), // 3: api.ArtifactsMessage
	nil,                      // 4: api.GraphState.NodeStatesEntry
	(graph.NodeState)(0),     // 5: graph.NodeState
	(*graph.Config)(nil),     // 6: graph.Config
}
var file_api_api_proto_depIdxs = []int32{
	4, // 0: api.GraphState.NodeStates:type_name -> api.GraphState.NodeStatesEntry
	5, // 1: api.GraphState.NodeStatesEntry.value:type_name -> graph.NodeState
	0, // 2: api.Graph.GetConfig:input_type -> api.Nothing
	0, // 3: api.Graph.GetState:input_type -> api.Nothing
	0, // 4: api.Graph.Run:input_type -> api.Nothing
	2, // 5: api.Node.Run:input_type -> api.NodeIdentifier
	2, // 6: api.Node.Reset:input_type -> api.NodeIdentifier
	2, // 7: api.Node.GetArtifacts:input_type -> api.NodeIdentifier
	6, // 8: api.Graph.GetConfig:output_type -> graph.Config
	1, // 9: api.Graph.GetState:output_type -> api.GraphState
	0, // 10: api.Graph.Run:output_type -> api.Nothing
	0, // 11: api.Node.Run:output_type -> api.Nothing
	0, // 12: api.Node.Reset:output_type -> api.Nothing
	3, // 13: api.Node.GetArtifacts:output_type -> api.ArtifactsMessage
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	file_api_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_api_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		MessageInfos:      file_api_api_proto_msgTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}
