// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	graph "pipegraph/graph"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nothing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nothing) Reset() {
	*x = Nothing{}
	mi := &file_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nothing) ProtoMessage() {}

func (x *Nothing) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nothing.ProtoReflect.Descriptor instead.
func (*Nothing) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

type NodeIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=Id,proto3,oneof" json:"Id,omitempty"` // optional string Name = 2;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIdentifier) Reset() {
	*x = NodeIdentifier{}
	mi := &file_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdentifier) ProtoMessage() {}

func (x *NodeIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdentifier.ProtoReflect.Descriptor instead.
func (*NodeIdentifier) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *NodeIdentifier) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type ArtifactsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        *string                `protobuf:"bytes,1,opt,name=Stdout,proto3,oneof" json:"Stdout,omitempty"`
	Stderr        *string                `protobuf:"bytes,2,opt,name=Stderr,proto3,oneof" json:"Stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactsMessage) Reset() {
	*x = ArtifactsMessage{}
	mi := &file_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactsMessage) ProtoMessage() {}

func (x *ArtifactsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactsMessage.ProtoReflect.Descriptor instead.
func (*ArtifactsMessage) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *ArtifactsMessage) GetStdout() string {
	if x != nil && x.Stdout != nil {
		return *x.Stdout
	}
	return ""
}

func (x *ArtifactsMessage) GetStderr() string {
	if x != nil && x.Stderr != nil {
		return *x.Stderr
	}
	return ""
}

type Updates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeStates    []*graph.NodeState     `protobuf:"bytes,1,rep,name=NodeStates,proto3" json:"NodeStates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Updates) Reset() {
	*x = Updates{}
	mi := &file_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Updates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Updates) ProtoMessage() {}

func (x *Updates) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Updates.ProtoReflect.Descriptor instead.
func (*Updates) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *Updates) GetNodeStates() []*graph.NodeState {
	if x != nil {
		return x.NodeStates
	}
	return nil
}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeStates    []*graph.NodeState     `protobuf:"bytes,1,rep,name=NodeStates,proto3" json:"NodeStates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_api_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *State) GetNodeStates() []*graph.NodeState {
	if x != nil {
		return x.NodeStates
	}
	return nil
}

var File_api_api_proto protoreflect.FileDescriptor

const file_api_api_proto_rawDesc = "" +
	"\n" +
	"\rapi/api.proto\x12\x03api\x1a\x12graph/config.proto\"\t\n" +
	"\aNothing\",\n" +
	"\x0eNodeIdentifier\x12\x13\n" +
	"\x02Id\x18\x01 \x01(\x04H\x00R\x02Id\x88\x01\x01B\x05\n" +
	"\x03_Id\"b\n" +
	"\x10ArtifactsMessage\x12\x1b\n" +
	"\x06Stdout\x18\x01 \x01(\tH\x00R\x06Stdout\x88\x01\x01\x12\x1b\n" +
	"\x06Stderr\x18\x02 \x01(\tH\x01R\x06Stderr\x88\x01\x01B\t\n" +
	"\a_StdoutB\t\n" +
	"\a_Stderr\";\n" +
	"\aUpdates\x120\n" +
	"\n" +
	"NodeStates\x18\x01 \x03(\v2\x10.graph.NodeStateR\n" +
	"NodeStates\"9\n" +
	"\x05State\x120\n" +
	"\n" +
	"NodeStates\x18\x01 \x03(\v2\x10.graph.NodeStateR\n" +
	"NodeStates2\x9a\x02\n" +
	"\x05Graph\x12(\n" +
	"\tGetConfig\x12\f.api.Nothing\x1a\r.graph.Config\x12(\n" +
	"\fCollectState\x12\f.api.Nothing\x1a\n" +
	".api.State\x121\n" +
	"\fRunReadyNode\x12\f.api.Nothing\x1a\x13.api.NodeIdentifier\x12/\n" +
	"\n" +
	"WaitRunEnd\x12\x13.api.NodeIdentifier\x1a\f.api.Updates\x12*\n" +
	"\aConnect\x12\x11.graph.EdgeConfig\x1a\f.api.Updates\x12-\n" +
	"\n" +
	"Disconnect\x12\x11.graph.EdgeConfig\x1a\f.api.Updates2\\\n" +
	"\x04Node\x12(\n" +
	"\x03Run\x12\x13.api.NodeIdentifier\x1a\f.api.Nothing\x12*\n" +
	"\x05Reset\x12\x13.api.NodeIdentifier\x1a\f.api.NothingB\x16Z\x14pipegraph/server/apib\x06proto3"

var (
	file_api_api_proto_rawDescOnce sync.Once
	file_api_api_proto_rawDescData []byte
)

func file_api_api_proto_rawDescGZIP() []byte {
	file_api_api_proto_rawDescOnce.Do(func() {
		file_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)))
	})
	return file_api_api_proto_rawDescData
}

var file_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_api_proto_goTypes = []any{
	(*Nothing)(nil),          // 0: api.Nothing
	(*NodeIdentifier)(nil),   // 1: api.NodeIdentifier
	(*ArtifactsMessage)(nil), // 2: api.ArtifactsMessage
	(*Updates)(nil),          // 3: api.Updates
	(*State)(nil),            // 4: api.State
	(*graph.NodeState)(nil),  // 5: graph.NodeState
	(*graph.EdgeConfig)(nil), // 6: graph.EdgeConfig
	(*graph.Config)(nil),     // 7: graph.Config
}
var file_api_api_proto_depIdxs = []int32{
	5,  // 0: api.Updates.NodeStates:type_name -> graph.NodeState
	5,  // 1: api.State.NodeStates:type_name -> graph.NodeState
	0,  // 2: api.Graph.GetConfig:input_type -> api.Nothing
	0,  // 3: api.Graph.CollectState:input_type -> api.Nothing
	0,  // 4: api.Graph.RunReadyNode:input_type -> api.Nothing
	1,  // 5: api.Graph.WaitRunEnd:input_type -> api.NodeIdentifier
	6,  // 6: api.Graph.Connect:input_type -> graph.EdgeConfig
	6,  // 7: api.Graph.Disconnect:input_type -> graph.EdgeConfig
	1,  // 8: api.Node.Run:input_type -> api.NodeIdentifier
	1,  // 9: api.Node.Reset:input_type -> api.NodeIdentifier
	7,  // 10: api.Graph.GetConfig:output_type -> graph.Config
	4,  // 11: api.Graph.CollectState:output_type -> api.State
	1,  // 12: api.Graph.RunReadyNode:output_type -> api.NodeIdentifier
	3,  // 13: api.Graph.WaitRunEnd:output_type -> api.Updates
	3,  // 14: api.Graph.Connect:output_type -> api.Updates
	3,  // 15: api.Graph.Disconnect:output_type -> api.Updates
	0,  // 16: api.Node.Run:output_type -> api.Nothing
	0,  // 17: api.Node.Reset:output_type -> api.Nothing
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	file_api_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_api_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		MessageInfos:      file_api_api_proto_msgTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}
